GET http://localhost:8080/todos

###

POST http://localhost:8080/todos
content-type: application/json

{
  "content": "Created Todo"
}

###

DELETE http://localhost:8080/todos?ids=

###

PATCH http://localhost:8080/todos/1/content
content-type: application/json

{
  "content": "Updated Todo"
}

###

PATCH http://localhost:8080/todos/1/completion
content-type: application/json

{
  "isComplete": true
}